### ISSUE TITLE
Segmentation fault on launch

### ISSUE THREAD

**Issue by santouits** [brndnmtthws/conky#1088]
**Issue**

I guess it should check if `XGetDefault(display, "Xft", "dpi")` returns NULL before passing it to atoi

**Information**

openbox, conky master

# Backtrace.
```gdb
__GI_____strtol_l_internal (nptr=0x0, endptr=endptr@entry=0x0, base=base@entry=10, group=group@entry=0, loc=0x7ffff77674c0 <_nl_global_locale>)
    at ../stdlib/strtol_l.c:292
292       while (ISSPACE (*s))
(gdb) bt
#0  __GI_____strtol_l_internal (nptr=0x0, endptr=endptr@entry=0x0, base=base@entry=10, group=group@entry=0, loc=0x7ffff77674c0 <_nl_global_locale>)
    at ../stdlib/strtol_l.c:292
#1  0x00007ffff75ea852 in __strtol (nptr=<optimized out>, endptr=endptr@entry=0x0, base=base@entry=10) at ../stdlib/strtol.c:106
#2  0x00007ffff75e75b0 in __GI_atoi (nptr=<optimized out>) at atoi.c:27
#3  0x000000000041d3f1 in X11_create_window () at ../src/conky.cc:2565
#4  0x000000000041e34f in initialisation (argc=1, argv=0x7fffffffddb8) at ../src/conky.cc:2917
#5  0x000000000040e55c in main (argc=1, argv=0x7fffffffddb8) at ../src/main.cc:353
```

**Comment by brndnmtthws** [comment]
Yeah I see that. I wonder why it's not returning a value.
