### ISSUE TITLE
out_to_ncurses : Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sebma** [brndnmtthws/conky#1197]
**Issue**

Conky crashes when using `out_to_ncurses = true`.

**Information**

Using Ubuntu 20.04.4 LTS with conky v1.10.8.

My .conkyrc : 

```lua
conky.config = {
-- conky configuration
	out_to_x = false,
	out_to_ncurses = true,
-- edited by Clapico : http://www.clapico.com
-- set to yes if you want Conky to be forked in the background
--	background = true,
-- X font when Xft is disabled, you can pick one with program xfontsel
--font 5x7
--font 6x10
--font 7x13
--font 8x13
--font 9x15
--font *mintsmild.se*
--font -*-*-*-*-*-*-34-*-*-*-*-*-*-*
-- Use Xft?
	use_xft = true,
-- Xft font when Xft is enabled
	font = 'Bitstream Vera Sans Mono:size=11',
-- Text alpha when using Xft
	xftalpha = 0.8,
-- Update interval in seconds
	update_interval = 1.0,
-- This is the number of times Conky will update before quitting.
-- Set to zero to run forever.
	total_run_times = 0,
-- Create own window instead of using desktop (required in nautilus)
--own_window no
-- Use double buffering (reduces flicker, may not work for everyone)
	double_buffer = true,
-- Minimum size of text area
	minimum_width = 480, minimum_height = 0,
	maximum_width = 600,
-- Draw shades?
	draw_shades = true,
-- Draw outlines?
--draw_outline no
-- Draw borders around text
	draw_borders = false,
--draw_graph_borders yes
-- Stippled borders?
--stippled_borders 8
-- border margins
--border_inner_margin 4
--border_outer_margin 8
-- border width
	border_width = 1,
-- Default colors and also border colors
	default_color = 'white',
	default_shade_color = 'black',
	default_outline_color = 'white',
-- own window options
	own_window = true,
	own_window_type = 'normal',
	own_window_argb_visual = true,
	own_window_transparent = true,
--own_window_hints undecorated,below,sticky,skip_taskbar,skip_pager
	own_window_hints = 'undecorated,below,skip_taskbar,skip_pager',
-- Text alignment, other possible values are commented
--alignment top_left
	alignment = 'top_right',
--alignment bottom_left
--alignment bottom_right
-- Gap between borders of screen and text
-- same thing as passing -x at command line
	gap_x = 0,
	gap_y = 0,
-- Subtract file system buffers from used memory?
	no_buffers = true,
-- set to yes if you want all text to be in uppercase
--uppercase no
-- number of cpu samples to average
-- set to 1 to disable averaging
	cpu_avg_samples = 2,
-- number of net samples to average
-- set to 1 to disable averaging
	net_avg_samples = 2,
-- Force UTF8? note that UTF8 support required XFT
--override_utf8_locale yes
-- Add spaces to keep things from moving about? This only affects certain objects.
	use_spacer = 'right',
-- colours
	color1 = 'blue',
--color1 F1C6FF
-- light blue
	color2 = '#E0D6BA',
-- orange
--E77320
	color3 = '#E0D6BA',
--color3 3BFE00
-- green
	color4 = '#78BF39',
-- red
	color5 = '#CC0000',
-- 
	color6 = '#888888',
-- yellow
	color7 = '#FC8820',
	text_buffer_size = 2048,
-- variable is given either in format $variable or in ${variable}. Latter
-- allows characters right after the variable and must be used in network
-- stuff because of an argument
-- stuff after 'TEXT' will be formatted on screen
-- ################################################################################################################################################
};

conky.text = [[
#${color white}Bienvenue sur $nodename
#${color white}${exec lsb_release -si} $sysname $kernel : ${exec lsb_release -sr} (${exec lsb_release -sc})
${color white}${exec lsb_release -sirc | tr "\n" " "}on ${color green}${time %A %d-%m-%Y}${color white} at ${color red}${time %T}
${color white}Wifi AP: ${color red}${wireless_bitrate wlan0} ${color white}Temperature ACPI: ${color1}${acpitemp}degres ${color white}Temperature sda: N/A
#${color white}Date: ${color1}${time %A %d %B %Y}${color white} a ${color red}${time %H:%M:%S}
#${color white}IP Ethernet: ${color1}${addr eth0}${color white}
#${color white}ESSID: ${color1}${wireless_essid wlan0}${color white} Signal WiFi: ${color1}${wireless_bitrate wlan0}
#${offset -5}${color white}${font StyleBats:style=CleanCut:size=12}q ${voffset -2}${font Bitstream Vera Sans Mono:style=Bold:size=11}Météo${font} ${hr}${color1}${execpi 1800 conkyForecast --location=FRXX5635 --template=/home/seb/.conky/conkyForecast.template}
#${color white}Load :${color1} $loadavg Nom du desktop: $desktop_name
${color white}CPU1 Utilisé :${color1} ${cpu cpu1}% ${color white}${cpubar cpu1}
${color white}${cpugraph cpu1 yellow FC8820}
${color white}CPU2 Utilisé :${color1} ${cpu cpu2}% ${color white}${cpubar cpu2}
${color white}${cpugraph cpu2 yellow FC8820}
${color white}CPU3 Utilisé :${color1} ${cpu cpu3}% ${color white}${cpubar cpu3}
${color white}${cpugraph cpu3 yellow FC8820}
${color white}CPU4 Utilisé :${color1} ${cpu cpu4}% ${color white}${cpubar cpu4}
${color white}${cpugraph cpu4 yellow FC8820}
${color white}Memoire RAM :${color1} $memperc% : $mem/$memmax ${color white}${membar}
${color white}${memgraph mem yellow FC8820}
#${color white}IO Writes :${color1} $memperc% : $mem/$memmax ${color white}${membar}
${color white}Disk I/O R/W :
${color white}${diskiograph /dev/sda yellow FC8820}
#${color white}Occupation du Swap :${color1} $swap/$swapmax - $swapperc% ${color white}${swapbar}
${color white}Occupation de /boot : ${color1}${fs_used /boot} / ${fs_size /boot} - ${fs_used_perc /boot}% ${color white}${fs_bar /boot}
${color white}Occupation de /: ${color1}${fs_used /} / ${fs_size /} - ${fs_used_perc /}% ${color white}${fs_bar /}
${color white}Occupation de /usr : ${color1}${fs_used /usr} / ${fs_size /usr} - ${fs_used_perc /usr}% ${color white}${fs_bar /usr}
${color white}Occupation de /usr/local : ${color1}${fs_used /usr/local} / ${fs_size /usr/local} - ${fs_used_perc /usr/local}% ${color white}${fs_bar /usr/local}
${color white}Occupation de /var : ${color1}${fs_used /var} / ${fs_size /var} - ${fs_used_perc /var}% ${color white}${fs_bar /var}
${color white}Occupation de /var/tmp : ${color1}${fs_used /var/tmp} / ${fs_size /var/tmp} - ${fs_used_perc /var/tmp}% ${color white}${fs_bar /var/tmp}
${color white}Occupation de /var/cache : ${color1}${fs_used /var/cache} / ${fs_size /var/cache} - ${fs_used_perc /var/cache}% ${color white}${fs_bar /var/cache}
${color white}Occupation de /opt : ${color1}${fs_used /opt} / ${fs_size /opt} - ${fs_used_perc /opt}% ${color white}${fs_bar /opt}
${color white}Occupation de /tmp : ${color1}${fs_used /tmp} / ${fs_size /tmp} - ${fs_used_perc /tmp}% ${color white}${fs_bar /tmp}
${color white}Occupation de /home : ${color1}${fs_used /home} / ${fs_size /home} - ${fs_used_perc /home}% ${color white}${fs_bar /home}
${color white}Occupation de /multimedia : ${color1}${fs_used /multimedia} / ${fs_size /multimedia} - ${fs_used_perc /multimedia}% ${color white}${fs_bar /multimedia}
#${color white}Processus :${color1} $processes ${color white} En cours :${color1} $running_processes
${color white}Utilisation du CPU
${offset 10}${color white}NAME ${alignr 50}PID ${alignr 20}%CPU
${offset 10}${color green}${top name 1} ${alignr 30}${top pid 1} ${alignr 15}${top cpu 1}
${offset 10}${color white}${top name 2} ${alignr 30}${top pid 2} ${alignr 15}${top cpu 2}
${offset 10}${color white}${top name 3} ${alignr 30}${top pid 3} ${alignr 15}${top cpu 3}
${offset 10}${color white}${top name 4} ${alignr 30}${top pid 4} ${alignr 15}${top cpu 4}
${offset 10}${color white}${top name 5} ${alignr 30}${top pid 5} ${alignr 15}${top cpu 5}
${color white}Utilisation de la Memoire
${offset 10}${color white}${color white}NAME ${alignr 100}PID ${alignr 50}SIZE ${alignr 20}%RAM
${offset 10}${color green}${top_mem name 1} ${alignr 45}${top_mem pid 1} ${alignr 25} ${top_mem mem_res 1} ${alignr 15}${top_mem mem 1}
${offset 10}${color white}${top_mem name 2} ${alignr 45}${top_mem pid 2} ${alignr 25} ${top_mem mem_res 2} ${alignr 15}${top_mem mem 2}
${offset 10}${color white}${top_mem name 3} ${alignr 45}${top_mem pid 3} ${alignr 25} ${top_mem mem_res 3} ${alignr 15}${top_mem mem 3}
${offset 10}${color white}${top_mem name 4} ${alignr 45}${top_mem pid 4} ${alignr 25} ${top_mem mem_res 4} ${alignr 15}${top_mem mem 4}
${offset 10}${color white}${top_mem name 5} ${alignr 45}${top_mem pid 5} ${alignr 25} ${top_mem mem_res 5} ${alignr 15}${top_mem mem 5}
]];
```

```gdb
$ gdb conky
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from conky...
(No debugging symbols found in conky)
warning: File "/home/sebastien/myConfig/.config/.gdbinit" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /home/sebastien/myConfig/.config/.gdbinit
line to your configuration file "/home/sebastien/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/sebastien/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
(gdb) run -c ~/.conkyrc
Starting program: /usr/bin/conky -c ~/.conkyrc
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
conky: drawing to single buffer
[New Thread 0x7ffff6b44700 (LWP 122406)]
                                        [New Thread 0x7ffff6343700 (LWP 122407)]
                                                                                [New Thread 0x7ffff5b42700 (LWP 122408)]
                                                                                                                        [New Thread 0x7ffff5341700 (LWP 122409)]
   [Detaching after fork from child process 122410]
[New Thread 0x7ffff4b40700 (LWP 122411)]
                                        [New Thread 0x7fffe7fff700 (LWP 122414)]
                                                                                [New Thread 0x7fffe77fe700 (LWP 122415)]

                                                                                                                        Thread 1 "conky" received signal SIGSEGV, Segmentation fault.
                        0x0000555555591328 in draw_each_line_inner(char*, int, int) ()
(gdb) bt full
#0  0x0000555555591328 in draw_each_line_inner(char*, int, int) ()
No symbol table info available.
#1  0x0000555555592c89 in ?? ()
No symbol table info available.
#2  0x0000555555592fa2 in ?? ()
No symbol table info available.
#3  0x00005555555943d7 in ?? ()
No symbol table info available.
#4  0x0000555555586be0 in main ()
No symbol table info available.
(gdb) q
A debugging session is active.

	Inferior 1 [process 122401] will be killed.

Quit anyway? (y or n) y
```

**Comment by mmuman** [comment]
Would you mind trying with a more recent version? I tried this same config with the current HEAD and it runs fine.
