### ISSUE TITLE
[Bug]: Assertion '__n < this->size()' failed.

### ISSUE THREAD

**Issue by musjj** [brndnmtthws/conky#1525]
### What happened?

When there's a font setting in `conky.text`, conky will crash when you try to reload the config.

### Version

1.18.1_pre compiled 2023-02-24 for Linux x86_64

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
conky.config = {
  background=true,
  update_interval=1,
  double_buffer=true,
  no_buffers=true,

  draw_shades=false,
  draw_outline=false,
  draw_borders=false,

  own_window=true,
  own_window_type="desktop",
  own_window_transparent=true,

  use_xft=true,
  font="Noto Sans:size=10",
}

conky.text = [[
${font Noto Sans:weight=Bold:size=90}${color0}\
${time %H:%M}\
]]
```

### Stack trace

```GDB
I tried to get stack trace, but `bt full` just outputs `No stack.`
```

### Relevant log output

```Shell
conky: desktop window (28d) is root window
conky: window type - desktop
conky: drawing to created window (0x3000001)
conky: drawing to double buffer
/usr/include/c++/12.2.1/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = x_font_list; _Alloc = std::allocator<x_font_list>; reference = x_font_list&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```
```

**Comment by bi4k8** [comment]
Here's the backtrace I get:

```bt
conky: src/fonts.cc:89: int font_height(): Assertion `selected_font < fonts.size()' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6e9f26c in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6e9f26c in  () at /usr/lib/libc.so.6
#1  0x00007ffff6e4fa08 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff6e38538 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff6e3845c in  () at /usr/lib/libc.so.6
#4  0x00007ffff6e483d6 in  () at /usr/lib/libc.so.6
#5  0x00005555555fa100 in font_height() () at src/fonts.cc:89
#6  0x000055555556f258 in update_text_area() () at src/conky.cc:858
#7  0x00005555555bea38 in X11_create_window() () at src/display-x11.cc:154
#8  0x00005555555bed35 in conky::display_output_x11::initialize() (this=0x5555557b4200 <conky::(anonymous namespace)::x11_output>) at src/display-x11.cc:220
#9  0x00005555555b97d6 in conky::initialize_display_outputs() () at src/display-output.cc:137
#10 0x0000555555574831 in initialisation(int, char**) (argc=3, argv=0x7fffffffdf48) at src/conky.cc:2268
#11 0x00005555555733ff in reload_config() () at src/conky.cc:1857
#12 0x0000555555572c18 in main_loop() () at src/conky.cc:1762
#13 0x000055555556cd93 in main(int, char**) (argc=3, argv=0x7fffffffdf48) at src/main.cc:355
```

It appears that while we clear fonts at some point when reloading config, we don't reset `selected_font` to 0.
