### ISSUE TITLE
[Bug]: Can't launch conky on wayland with swaywm as compositor

### ISSUE THREAD

**Issue by TheSaintDiratof** [brndnmtthws/conky#1707]
### What happened?

conky doesn't appear on screen

### Version

1.19.6

### Which OS/distro are you seeing the problem on?

Linux (other)

### Conky config

```Lua
conky.config = {
  out_to_wayland = true,
  out_to_x = false,
}
conky.text = ""
```

### Stack trace

```GDB
#0  0x00007ffff7511ab7 in clock_nanosleep@GLIBC_2.2.5 () from /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff7523e57 in nanosleep () from /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libc.so.6
No symbol table info available.
#2  0x000000000042449e in main_loop() ()
No symbol table info available.
#3  0x00000000004169de in main ()
No symbol table info available.
```

### Relevant log output

```Shell
conky: Unknown setting 'out_to_wayland'
conky: invalid setting of type 'table'
Unable to find a usable display output.
```

**Comment by uberbrodt** [comment]
I ran into this on Fedora 39 (Sway spin). The version of Conky shipped by the distro does not have the Wayland build flag enabled. Compiling from source and enabling the Wayland flag works for me.

**Comment by Caellian** [comment]
Closing as wontfix because
```
conky: Unknown setting 'out_to_wayland'
```
indicates conky was built without wayland support as uberbrodt said.
