### ISSUE TITLE
bspwm implementation

### ISSUE THREAD

**Issue by cmizzi** [brndnmtthws/conky#424]
While using `Conky` with `bspwm`, an error occurred when the system is started : 

```conky: desktop window (400005) is subwindow of root window (ed)
conky: window type - override
conky: drawing to created window (0xe00002)
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  1 (X_CreateWindow)
  Serial number of failed request:  195
  Current serial number in output stream:  197
```

When the system is booting, `conky` starts as well but when I stop it and re-create instance, this error is thrown. I need to use `override` window type because I want `conky` to be placed below others windows without being considered as window. `dock` or `panel` modes are taking `conky` above all others windows...

**Comment by easysid** [comment]
Did you try `desktop` window type? I use it on bspwm and it works fine.

**Comment by ShionRyuu** [comment]
conky report error like above when window type set to override

```bash
$ conky
conky: desktop window (1800011) is subwindow of root window (54b)
conky: window type - override
conky: drawing to created window (0x3800001)
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  1 (X_CreateWindow)
  Serial number of failed request:  151
  Current serial number in output stream:  155
$ conky
conky: desktop window (1800011) is subwindow of root window (54b)
conky: window type - normal
conky: drawing to created window (0x6200001)
conky: drawing to double buffer
conky: desktop window (1800011) is subwindow of root window (54b)
conky: window type - normal
conky: drawing to created window (0x6400001)
conky: drawing to double buffer
$ conky
conky: desktop window (1800011) is subwindow of root window (54b)
conky: window type - desktop
conky: drawing to created window (0x6400001)
conky: drawing to double buffer
conky: forked to background, pid is 28727
```

**Comment by lasers** [comment]
Hi. If you're still experiencing this, can you `gdb conky` + (gdb) `run` until it crashes, then (gdb) `bt full` to print out a backtrace. Paste it here. Thanks.

**Comment by lasers** [comment]
@ShionRyuu Can you try the current master? I do not have this issue on `bspwm`. Thanks.

```bash
git clone https://github.com/brndnmtthws/conky
cd conky
mkdir -p build
cd build
cmake ..
make -j4  # 4 cores to run in parallel
src/conky -c ~/conky.conf # <-- your config goes here
```

**Comment by lasers** [comment]
@cmizzi You too. I thought @ShionRyuu was the author of this issue. Oof.

**Comment by cmizzi** [comment]
I've got the following error message. It doesn't appear when window type is set to `desktop`.

```
conky: desktop window (400005) is subwindow of root window (135)
conky: window type - override
conky: drawing to created window (0x1600002)
conky: X Error: type 0 Display 56540f113790 XID 4194309 serial 206 error_code 8 request_code 1 minor_code 0 other Display: 56540f113790

[1]    25365 abort (core dumped)  src/conky -c ~/.conkyrc
```

**Comment by lasers** [comment]
Can you share your config? Also, try `src/conky` without the `-c ~/.conkyrc` to rule out your config (or something in your config). I installed bspwm yesterday to test current master and had no issue.

**Comment by lasers** [comment]
* Run `gdb conky`.
* Run `(gdb) run -c ~/.conkyrc`.
* When it crashes, run `(gdb) bt full`.
* We want that backtrace.
* Thanks.

**Comment by cmizzi** [comment]
```gdb
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from conky...done.
(gdb) run -c ~/.conkyrc
Starting program: /usr/local/bin/conky -c ~/.conkyrc
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
conky: desktop window (400005) is subwindow of root window (161)
conky: window type - override
conky: drawing to created window (0x1600002)
conky: X Error: type 0 Display 55555587c790 XID 4194309 serial 176 error_code 8 request_code 1 minor_code 0 other Display: 55555587c790


Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 93824995209888, 140737488341664, 140737488341696, 93824995381984, 140737488344980, 0, 93824995381984, 140737488341864, 1, 0, 93824995209888, 140737488341664, 140737303932164, 93824995600336, 0}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff502c801 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x500000000, sa_sigaction = 0x500000000}, sa_mask = {__val = {93824992808624, 0, 140737304293821, 93824995209696, 140737307838080, 3432, 1, 140737307838211, 140737304301393, 1, 140737307838080, 10, 93824995542928, 4194309, 176, 1}}, sa_flags = -184052733,
          sa_restorer = 0x8}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#2  0x00005555555c89a9 in x11_error_handler (d=0x55555587c790, err=<optimized out>) at /tmp/conky/src/x11.cc:379
No locals.
#3  0x00007ffff726a8ba in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#4  0x00007ffff72677eb in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#5  0x00007ffff7267895 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#6  0x00007ffff72687f0 in _XReply () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#7  0x00007ffff725e716 in XQueryExtension () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#8  0x00007ffff7251ee6 in XInitExtension () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#9  0x00007ffff7024fdf in XextAddDisplay () from /usr/lib/x86_64-linux-gnu/libXext.so.6
No symbol table info available.
#10 0x00007ffff7024058 in XdbeQueryExtension () from /usr/lib/x86_64-linux-gnu/libXext.so.6
No symbol table info available.
#11 0x00005555555c9384 in priv::use_xdbe_setting::set_up (this=<optimized out>, l=...) at /tmp/conky/src/x11.cc:133
        major = 1434907088
        minor = 21845
#12 0x00005555555ca5db in priv::use_xdbe_setting::lua_setter (this=0x555555821e60 <use_xdbe>, l=..., init=<optimized out>) at /tmp/conky/src/x11.cc:157
        s = {L = 0x55555586f1d0, n = 4}
#13 0x00005555555a5927 in conky::priv::config_setting_base::process_setting (l=..., init=<optimized out>) at /tmp/conky/src/setting.cc:138
        s = {L = 0x55555586f1d0, n = 3}
        ptr = <optimized out>
#14 0x00005555555a5fdd in conky::set_config_settings (l=...) at /tmp/conky/src/setting.cc:225
        i = 0x555555821e60 <use_xdbe>
        __for_range = std::vector of length 114, capacity 114 = {0x5555557fb5a0 <no_buffers>, 0x5555557fb540 <bar_fill[abi:cxx11]>, 0x5555557fb4e0 <bar_unfill[abi:cxx11]>, 0x5555557fb480 <github_token[abi:cxx11]>, 0x5555557fc700 <disable_auto_reload>, 0x5555557fc620 <use_spacer>, 0x5555557fc5e0 <short_units>,
          0x5555557fc5a0 <format_human_readable>, 0x5555557fbee0 <out_to_stdout>, 0x5555557fc560 <out_to_stderr>, 0x5555557fc520 <extra_newline>, 0x5555557fbe60 <update_interval>, 0x5555557fbe00 <update_interval_on_battery>, 0x5555557fbda0 <detect_battery[abi:cxx11]>, 0x5555557fbd60 <music_player_interval>,
          0x5555557fc4c0 <max_text_width>, 0x5555557fc460 <stuff_in_uppercase>, 0x5555557fc400 <total_run_times>, 0x5555557fc3c0 <fork_to_background>, 0x5555557fb8c0 <cpu_avg_samples>, 0x5555557fb880 <net_avg_samples>, 0x5555557fb840 <diskio_avg_samples>, 0x5555557fc360 <overwrite_file>,
          0x5555557fc300 <append_file>, 0x5555557fc2c0 <show_graph_scale>, 0x5555557fc280 <show_graph_range>, 0x5555557fc240 <gap_x>, 0x5555557fc200 <gap_y>, 0x5555557fc1c0 <draw_borders>, 0x5555557fc180 <draw_graph_borders>, 0x5555557fb800 <stippled_borders>, 0x5555557fc140 <draw_shades>,
          0x5555557fc100 <draw_outline>, 0x5555557fc0a0 <minimum_height>, 0x5555557fc060 <minimum_width>, 0x5555557fc020 <maximum_width>, 0x5555557fb7c0 <utf8_mode>, 0x5555557fb780 <max_user_text>, 0x5555557fb740 <text_buffer_size>, 0x5555557fbfe0 <pad_percents>, 0x555555806240 <current_mail_spool>,
          0x555555806300 <(anonymous namespace)::imap>, 0x5555558062a0 <(anonymous namespace)::pop3>, 0x55555581e9a0 <if_up_strictness>, 0x55555581ea60 <(anonymous namespace)::_template>, 0x55555581eab8 <(anonymous namespace)::_template+88>, 0x55555581eb10 <(anonymous namespace)::_template+176>,
          0x55555581eb68 <(anonymous namespace)::_template+264>, 0x55555581ebc0 <(anonymous namespace)::_template+352>, 0x55555581ec18 <(anonymous namespace)::_template+440>, 0x55555581ec70 <(anonymous namespace)::_template+528>, 0x55555581ecc8 <(anonymous namespace)::_template+616>,
          0x55555581ed20 <(anonymous namespace)::_template+704>, 0x55555581ed78 <(anonymous namespace)::_template+792>, 0x55555581f0e0 <(anonymous namespace)::default_bar_width>, 0x55555581f0a0 <(anonymous namespace)::default_bar_height>, 0x55555581f060 <(anonymous namespace)::default_graph_width>,
          0x55555581f020 <(anonymous namespace)::default_graph_height>, 0x55555581efe0 <(anonymous namespace)::default_gauge_width>, 0x55555581efa0 <(anonymous namespace)::default_gauge_height>, 0x55555581ef40 <(anonymous namespace)::console_graph_ticks>, 0x55555581f140 <output_unit>,
          0x55555581f1e0 <times_in_seconds>, 0x55555581f280 <top_name_width>, 0x55555581f240 <top_name_verbose>, 0x555555820340 <conky::asdf>, 0x555555820580 <(anonymous namespace)::lua_load>, 0x555555820520 <(anonymous namespace)::lua_startup_hook>, 0x5555558204c0 <(anonymous namespace)::lua_shutdown_hook>,
          0x555555820460 <(anonymous namespace)::lua_draw_hook_pre>, 0x555555820400 <(anonymous namespace)::lua_draw_hook_post>, 0x555555821be0 <top_cpu_separate>, 0x555555821d60 <(anonymous namespace)::mpd_port>, 0x555555821d00 <(anonymous namespace)::mpd_host>, 0x555555821ca0 <(anonymous namespace)::mpd_password>,
          0x555555821da0 <max_port_monitor_connections>, 0x555555822640 <text_alignment>, 0x5555558225e0 <display_name[abi:cxx11]>, 0x5555558225a0 <head_index>, 0x555555822560 <out_to_x>, 0x5555558222e0 <color>, 0x555555822320 <color+64>, 0x555555822360 <color+128>, 0x5555558223a0 <color+192>,
          0x5555558223e0 <color+256>, 0x555555822420 <color+320>, 0x555555822460 <color+384>, 0x5555558224a0 <color+448>, 0x5555558224e0 <color+512>, 0x555555822520 <color+576>, 0x5555558222a0 <default_color>, 0x555555822260 <default_shade_color>, 0x555555822220 <default_outline_color>,
          0x5555558221e0 <border_inner_margin>, 0x5555558221a0 <border_outer_margin>, 0x555555822160 <border_width>, 0x555555822120 <use_xft>, 0x5555558220e0 <set_transparent>, 0x555555822080 <own_window_class[abi:cxx11]>, 0x555555822020 <own_window_title[abi:cxx11]>, 0x555555821fe0 <own_window_type>,
          0x555555821fa0 <own_window_hints>, 0x555555821f60 <background_colour>, 0x555555821f20 <use_argb_visual>, 0x555555821ee0 <own_window_argb_value>, 0x555555821ea0 <own_window>, 0x555555821e60 <use_xdbe>, 0x555555821e00 <imlib_cache_size>, 0x555555822c20 <font>,
          0x555555822ca0 <(anonymous namespace)::xftalpha>, 0x555555822d80 <hddtemp_host>, 0x555555822d20 <hddtemp_port>, 0x555555825840 <(anonymous namespace)::imlib_cache_flush_interval>, 0x555555825a60 <out_to_ncurses>}
        __for_begin = <optimized out>
        __for_end = <optimized out>
        v = std::vector of length 114, capacity 114 = {0x5555557fb5a0 <no_buffers>, 0x5555557fb540 <bar_fill[abi:cxx11]>, 0x5555557fb4e0 <bar_unfill[abi:cxx11]>, 0x5555557fb480 <github_token[abi:cxx11]>, 0x5555557fc700 <disable_auto_reload>, 0x5555557fc620 <use_spacer>, 0x5555557fc5e0 <short_units>,
          0x5555557fc5a0 <format_human_readable>, 0x5555557fbee0 <out_to_stdout>, 0x5555557fc560 <out_to_stderr>, 0x5555557fc520 <extra_newline>, 0x5555557fbe60 <update_interval>, 0x5555557fbe00 <update_interval_on_battery>, 0x5555557fbda0 <detect_battery[abi:cxx11]>, 0x5555557fbd60 <music_player_interval>,
          0x5555557fc4c0 <max_text_width>, 0x5555557fc460 <stuff_in_uppercase>, 0x5555557fc400 <total_run_times>, 0x5555557fc3c0 <fork_to_background>, 0x5555557fb8c0 <cpu_avg_samples>, 0x5555557fb880 <net_avg_samples>, 0x5555557fb840 <diskio_avg_samples>, 0x5555557fc360 <overwrite_file>,
          0x5555557fc300 <append_file>, 0x5555557fc2c0 <show_graph_scale>, 0x5555557fc280 <show_graph_range>, 0x5555557fc240 <gap_x>, 0x5555557fc200 <gap_y>, 0x5555557fc1c0 <draw_borders>, 0x5555557fc180 <draw_graph_borders>, 0x5555557fb800 <stippled_borders>, 0x5555557fc140 <draw_shades>,
          0x5555557fc100 <draw_outline>, 0x5555557fc0a0 <minimum_height>, 0x5555557fc060 <minimum_width>, 0x5555557fc020 <maximum_width>, 0x5555557fb7c0 <utf8_mode>, 0x5555557fb780 <max_user_text>, 0x5555557fb740 <text_buffer_size>, 0x5555557fbfe0 <pad_percents>, 0x555555806240 <current_mail_spool>,
          0x555555806300 <(anonymous namespace)::imap>, 0x5555558062a0 <(anonymous namespace)::pop3>, 0x55555581e9a0 <if_up_strictness>, 0x55555581ea60 <(anonymous namespace)::_template>, 0x55555581eab8 <(anonymous namespace)::_template+88>, 0x55555581eb10 <(anonymous namespace)::_template+176>,
          0x55555581eb68 <(anonymous namespace)::_template+264>, 0x55555581ebc0 <(anonymous namespace)::_template+352>, 0x55555581ec18 <(anonymous namespace)::_template+440>, 0x55555581ec70 <(anonymous namespace)::_template+528>, 0x55555581ecc8 <(anonymous namespace)::_template+616>,
          0x55555581ed20 <(anonymous namespace)::_template+704>, 0x55555581ed78 <(anonymous namespace)::_template+792>, 0x55555581f0e0 <(anonymous namespace)::default_bar_width>, 0x55555581f0a0 <(anonymous namespace)::default_bar_height>, 0x55555581f060 <(anonymous namespace)::default_graph_width>,
          0x55555581f020 <(anonymous namespace)::default_graph_height>, 0x55555581efe0 <(anonymous namespace)::default_gauge_width>, 0x55555581efa0 <(anonymous namespace)::default_gauge_height>, 0x55555581ef40 <(anonymous namespace)::console_graph_ticks>, 0x55555581f140 <output_unit>,
          0x55555581f1e0 <times_in_seconds>, 0x55555581f280 <top_name_width>, 0x55555581f240 <top_name_verbose>, 0x555555820340 <conky::asdf>, 0x555555820580 <(anonymous namespace)::lua_load>, 0x555555820520 <(anonymous namespace)::lua_startup_hook>, 0x5555558204c0 <(anonymous namespace)::lua_shutdown_hook>,
          0x555555820460 <(anonymous namespace)::lua_draw_hook_pre>, 0x555555820400 <(anonymous namespace)::lua_draw_hook_post>, 0x555555821be0 <top_cpu_separate>, 0x555555821d60 <(anonymous namespace)::mpd_port>, 0x555555821d00 <(anonymous namespace)::mpd_host>, 0x555555821ca0 <(anonymous namespace)::mpd_password>,
          0x555555821da0 <max_port_monitor_connections>, 0x555555822640 <text_alignment>, 0x5555558225e0 <display_name[abi:cxx11]>, 0x5555558225a0 <head_index>, 0x555555822560 <out_to_x>, 0x5555558222e0 <color>, 0x555555822320 <color+64>, 0x555555822360 <color+128>, 0x5555558223a0 <color+192>,
          0x5555558223e0 <color+256>, 0x555555822420 <color+320>, 0x555555822460 <color+384>, 0x5555558224a0 <color+448>, 0x5555558224e0 <color+512>, 0x555555822520 <color+576>, 0x5555558222a0 <default_color>, 0x555555822260 <default_shade_color>, 0x555555822220 <default_outline_color>,
          0x5555558221e0 <border_inner_margin>, 0x5555558221a0 <border_outer_margin>, 0x555555822160 <border_width>, 0x555555822120 <use_xft>, 0x5555558220e0 <set_transparent>, 0x555555822080 <own_window_class[abi:cxx11]>, 0x555555822020 <own_window_title[abi:cxx11]>, 0x555555821fe0 <own_window_type>,
          0x555555821fa0 <own_window_hints>, 0x555555821f60 <background_colour>, 0x555555821f20 <use_argb_visual>, 0x555555821ee0 <own_window_argb_value>, 0x555555821ea0 <own_window>, 0x555555821e60 <use_xdbe>, 0x555555821e00 <imlib_cache_size>, 0x555555822c20 <font>,
          0x555555822ca0 <(anonymous namespace)::xftalpha>, 0x555555822d80 <hddtemp_host>, 0x555555822d20 <hddtemp_port>, 0x555555825840 <(anonymous namespace)::imlib_cache_flush_interval>, 0x555555825a60 <out_to_ncurses>}
        s = {L = <optimized out>, n = 0}
#15 0x00005555555730ac in initialisation (argc=3, argv=0x7fffffffd308) at /tmp/conky/src/conky.cc:3000
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        oact = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
#16 0x00005555555650eb in main (argc=3, argv=0x7fffffffd308) at /tmp/conky/src/conky.cc:3154
        curl_global = <optimized out>
```
