### ISSUE TITLE
$execigauge creating seg fault

### ISSUE THREAD

**Issue by ylwhatt** [brndnmtthws/conky#690]
so when i use execgauge it works but execigauge does not and then seg faults out
i use:
${execgauge 18,36 df | grep p7 | cut -c 46-48} 
and it works but no updating
if i use:
${execigauge 10 18,36 df | grep p7 | cut -c 46-48}
it does not... do i need to include anything else? any ideas how to fix it other than to downgrade?

**Comment by lasers** [comment]
```
$ conky -c default.conf
conky: desktop window (25a) is root window
conky: window type - desktop
conky: drawing to created window (0x4000001)
free(): invalid pointer
[1]    32052 abort (core dumped)  conky -c default.conf
```

Output from gdb's `bt full`:
```
Starting program: /usr/local/bin/conky -c ~/Documents/Conky/default.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
conky: desktop window (25a) is root window
conky: window type - desktop
conky: drawing to created window (0x4000001)
free(): invalid pointer

Program received signal SIGABRT, Aborted.
0x00007ffff65ead7f in raise () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff65ead7f in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff65d5672 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007ffff662d878 in __libc_message () from /usr/lib/libc.so.6
No symbol table info available.
#3  0x00007ffff663418a in malloc_printerr () from /usr/lib/libc.so.6
No symbol table info available.
#4  0x00007ffff663597c in _int_free () from /usr/lib/libc.so.6
No symbol table info available.
#5  0x000055555558f4e8 in scan_exec_arg(text_object*, char const*, unsigned int) ()
No symbol table info available.
#6  0x0000555555588073 in construct_text_object(char*, char const*, long, void**, void*) ()
No symbol table info available.
#7  0x000055555558d4be in extract_variable_text_internal(text_object*, char const*) ()
No symbol table info available.
#8  0x000055555557e3dd in initialisation(int, char**) ()
No symbol table info available.
#9  0x000055555556da00 in main ()
No symbol table info available.
(gdb)
```
